---
- block:

  - name: yum dependencies
    yum: name={{ item }} state=present
    with_items:
      - pygpgme
      - yum-utils

  - name: install lacework yum repo
      get_url:
        url: "https://packages.lacework.net/RPMS/x86_64/lacework-prod.repo"
        dest: "/etc/yum.repos.d/lacework-prod.repo"
        owner: root
        group: root
        mode: 0644

  - name: install Lacework agent
    yum: name=lacework state=latest

  tags:
    - lacework
